/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_PREFIX "/usr"
#define CONFIG_QEMU_BINDIR "/usr/bin"
#define CONFIG_QEMU_MANDIR "/usr/share/man"
#define CONFIG_QEMU_DATADIR "/usr/share/qemu"
#define CONFIG_QEMU_SYSCONFDIR "/usr/etc"
#define CONFIG_QEMU_DOCDIR "/usr/share/doc/qemu"
#define CONFIG_QEMU_CONFDIR "/usr/etc/qemu"
#define HOST_X86_64 1
#define HOST_LONG_BITS 64
#define CONFIG_POSIX 1
#define CONFIG_LINUX 1
#define CONFIG_SLIRP 1
#define CONFIG_AC97 1
#define CONFIG_ES1370 1
#define CONFIG_SB16 1
#define CONFIG_HDA 1
#define CONFIG_AUDIO_DRIVERS \
    &oss_audio_driver,\

#define CONFIG_OSS 1
#define CONFIG_BDRV_WHITELIST \
    NULL
#define CONFIG_VNC_TLS 1
#define CONFIG_VNC_SASL 1
#define CONFIG_FNMATCH 1
#define CONFIG_UUID 1
#define QEMU_VERSION "0.14.1"
#define QEMU_PKGVERSION " (qemu-kvm-0.14.1)"
#define CONFIG_CURSES 1
#define CONFIG_ATFILE 1
#define CONFIG_UTIMENSAT 1
#define CONFIG_PIPE2 1
#define CONFIG_ACCEPT4 1
#define CONFIG_SPLICE 1
#define CONFIG_EVENTFD 1
#define CONFIG_FALLOCATE 1
#define CONFIG_SYNC_FILE_RANGE 1
#define CONFIG_FIEMAP 1
#define CONFIG_DUP3 1
#define CONFIG_INOTIFY 1
#define CONFIG_INOTIFY1 1
#define CONFIG_BYTESWAP_H 1
#define CONFIG_CURL 1
#define CONFIG_ATTR 1
#define CONFIG_VIRTFS 1
#define CONFIG_IOVEC 1
#define CONFIG_PREADV 1
#define CONFIG_SIGNALFD 1
#define CONFIG_GCC_ATTRIBUTE_WARN_UNUSED_RESULT 1
#define CONFIG_FDATASYNC 1
#define CONFIG_CPU_EMULATION 1
#define CONFIG_MADVISE 1
#define CONFIG_POSIX_MADVISE 1
#define CONFIG_UNAME_RELEASE ""
#define CONFIG_ZERO_MALLOC 1
#define CONFIG_TRACE_FILE trace
